name: Build Application

# 環境変数の定義
env:
  NODE_VERSION: '20.x'
  PNPM_VERSION: '10.4.1'
  RUST_TOOLCHAIN: 'stable'

# トリガー条件
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
    tags-ignore:
      - 'v*'  # タグがプッシュされた場合は実行しない (release.ymlが担当)
  pull_request:
    branches: [ main ]
  # 手動実行のオプション
  workflow_dispatch:
    inputs:
      platform:
        description: 'Build platform (all, windows, macos, linux)'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - windows
        - macos
        - linux

jobs:
  # ビルド実行の判断
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # 直前のコミットを取得するために必要

      - name: Check commit message for build tag
        id: check
        run: |
          echo "GitHub Event: ${{ github.event_name }}"
          
          # 手動実行の場合は常に実行
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Manual dispatch - always run"
            echo "should-run=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # コミットメッセージをチェック
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit Message: $COMMIT_MSG"
          
          if [[ "${COMMIT_MSG^^}" == *"[BUILD]"* ]]; then
            echo "Build tag detected"
            echo "should-run=true" >> $GITHUB_OUTPUT
          else
            echo "No build tag found"
            echo "should-run=false" >> $GITHUB_OUTPUT
          fi
  
  # アプリケーションビルド
  build:
    needs: check-commit-message
    if: ${{ needs.check-commit-message.outputs.should-run == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            name: windows
          - platform: macos-latest
            name: macos
          - platform: ubuntu-latest
            name: linux
    
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check platform selection
        id: platform-check
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.platform != 'all' && github.event.inputs.platform != matrix.name }}
        run: |
          echo "Skipping build for ${{ matrix.name }} platform as per selection"
          exit 0
      
      # Node.js環境の設定
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      # pnpmのインストールと設定
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false
      
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
          
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        run: pnpm install
      
      # Rust環境の設定
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      
      # Windows固有の設定
      - name: Install WebView2 (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          $installer = "$env:TEMP\MicrosoftEdgeWebView2Setup.exe"
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile $installer
          Start-Process -FilePath $installer -Args "/silent /install" -Verb RunAs -Wait
      
      # macOS固有の設定
      - name: Install macOS dependencies
        if: matrix.platform == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin
          brew install jq
      
      # Linux固有の設定
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      
      # Tauri CLIのインストール
      - name: Install Tauri CLI
        run: pnpm add -D @tauri-apps/cli
      
      - name: Show environment info
        run: |
          node --version
          pnpm --version
          rustc --version
          cargo --version
          
      # アプリのビルド
      - name: Build the app
        id: build
        run: pnpm tauri build
        continue-on-error: false
      
      # Windows用アーティファクトのアップロード
      - name: Upload Windows artifacts
        if: matrix.platform == 'windows-latest' && steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe
          retention-days: 7
      
      # macOS用アーティファクトのアップロード
      - name: Upload macOS artifacts
        if: matrix.platform == 'macos-latest' && steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: macos-installer
          path: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/macos/*.app
          retention-days: 7
      
      # Linux用アーティファクトのアップロード
      - name: Upload Linux artifacts
        if: matrix.platform == 'ubuntu-latest' && steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: linux-installer
          path: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/appimage/*.AppImage
          retention-days: 7

      # ビルド結果の通知（Slackやメール通知などを追加可能）
      - name: Notify build status
        if: always()
        run: |
          if [[ "${{ steps.build.outcome }}" == "success" ]]; then
            echo "✅ Build successful for ${{ matrix.name }}"
          else
            echo "❌ Build failed for ${{ matrix.name }}"
          fi
