name: Release

on:
  push:
    tags:
      - 'v*'
  # 手動リリース作成のオプション
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. 1.0.0)'
        required: true
        type: string
      platform:
        description: 'Release platform (all, windows, macos, linux)'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - windows
        - macos
        - linux

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.id }}
      upload_url: ${{ steps.create-release.outputs.upload_url }}
      version: ${{ steps.get-version.outputs.version }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version from tag
        id: get-version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Get version from input
        id: get-input-version
        if: github.event_name == 'workflow_dispatch'
        run: echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
      
      - name: Set final version
        id: set-version
        run: |
          if [ "${{ steps.get-version.outputs.version }}" != "" ]; then
            echo "version=${{ steps.get-version.outputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ steps.get-input-version.outputs.version }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.set-version.outputs.version }}
          release_name: Release v${{ steps.set-version.outputs.version }}
          draft: true
          prerelease: false

  build-release:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - platform: windows-latest
            name: windows
            artifact_name: image-viewer_Windows_x64
            binary_path: "src-tauri/target/release/image-viewer.exe"
            asset_name: image-viewer-windows-x64
          - platform: macos-latest
            name: macos
            artifact_name: image-viewer_macOS_x64
            binary_path: "src-tauri/target/release/image-viewer"
            asset_name: image-viewer-macos-x64
          - platform: ubuntu-latest
            name: linux
            artifact_name: image-viewer_Linux_x64
            binary_path: "src-tauri/target/release/image-viewer"
            asset_name: image-viewer-linux-x64
    
    # 手動実行で特定のプラットフォームが選択された場合、その条件に合致するものだけを実行
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == matrix.name }}
    
    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.4.1
          run_install: false
      
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
          
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      
      # Windows固有の設定
      - name: Install WebView2
        if: matrix.platform == 'windows-latest'
        run: |
          $installer = "$env:TEMP\MicrosoftEdgeWebView2Setup.exe"
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile $installer
          Start-Process -FilePath $installer -Args "/silent /install" -Verb RunAs -Wait
      
      # macOS固有の設定
      - name: Install macOS dependencies
        if: matrix.platform == 'macos-latest'
        run: |
          rustup target add aarch64-apple-darwin
          brew install jq
      
      # Linux固有の設定
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: Install Tauri CLI
        run: pnpm add -D @tauri-apps/cli
      
      - name: Build the app
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        run: pnpm tauri build
      
      - name: Create release archives
        shell: bash
        run: |
          mkdir -p release-archives
          
          if [ "${{ matrix.platform }}" = "windows-latest" ]; then
            # Windows インストーラーを移動
            cp src-tauri/target/release/bundle/msi/*.msi release-archives/${{ matrix.asset_name }}.msi
            cp src-tauri/target/release/bundle/nsis/*.exe release-archives/${{ matrix.asset_name }}-setup.exe
          elif [ "${{ matrix.platform }}" = "macos-latest" ]; then
            # macOS バンドルを移動
            cp -r src-tauri/target/release/bundle/dmg/*.dmg release-archives/${{ matrix.asset_name }}.dmg
            # Universal Binary ビルド結果を移動 (もし設定していれば)
            if [ -d "src-tauri/target/universal-apple-darwin/release/bundle/dmg" ]; then
              cp -r src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg release-archives/${{ matrix.asset_name }}-universal.dmg
            fi
          elif [ "${{ matrix.platform }}" = "ubuntu-latest" ]; then
            # Linux パッケージを移動
            cp src-tauri/target/release/bundle/deb/*.deb release-archives/${{ matrix.asset_name }}.deb
            cp src-tauri/target/release/bundle/appimage/*.AppImage release-archives/${{ matrix.asset_name }}.AppImage
          fi
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: release-archives
      
  publish-release:
    needs: [create-release, build-release]
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -type f -exec cp {} release-assets/ \;
          ls -la release-assets/
      
      - name: Publish release assets
        uses: softprops/action-gh-release@v1
        with:
          files: release-assets/*
          tag_name: v${{ needs.create-release.outputs.version }}
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
